# Generated by Django 5.2.13 on 2026-09-08 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, unique=True, verbose_name="Nome"),
                ),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "tipo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Técnico Integrado", "Técnico Integrado"),
                            ("Técnico Subsequente", "Técnico Subsequente"),
                            ("Técnico (PROEJA)", "Técnico (PROEJA)"),
                            ("Licenciatura", "Licenciatura"),
                            ("Tecnologia", "Tecnologia"),
                        ],
                        max_length=40,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "modalidade",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Modalidade"
                    ),
                ),
                (
                    "turno",
                    models.CharField(blank=True, max_length=200, verbose_name="Turno"),
                ),
                (
                    "carga_horaria",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Carga horária"
                    ),
                ),
                (
                    "duracao",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Duração"
                    ),
                ),
                (
                    "coordenador",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Coordenador(a)"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                ("lattes", models.URLField(blank=True, verbose_name="Lattes")),
                ("posicao", models.IntegerField(default=9999, verbose_name="Posição")),
                (
                    "ppcs",
                    models.JSONField(blank=True, default=list, verbose_name="PPCs"),
                ),
            ],
            options={
                "verbose_name": "Curso",
                "verbose_name_plural": "Cursos",
                "ordering": ["posicao", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, unique=True, verbose_name="Nome"),
                ),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
            ],
            options={
                "verbose_name": "Professor",
                "verbose_name_plural": "Professores",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Sala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, unique=True, verbose_name="Nome"),
                ),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "predio",
                    models.CharField(blank=True, max_length=200, verbose_name="Prédio"),
                ),
            ],
            options={
                "verbose_name": "Sala",
                "verbose_name_plural": "Salas",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Versao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "versao",
                    models.CharField(max_length=40, unique=True, verbose_name="Versão"),
                ),
                ("inicio", models.DateField(verbose_name="Início")),
                ("fim", models.DateField(blank=True, null=True, verbose_name="Fim")),
                (
                    "atual",
                    models.BooleanField(default=False, verbose_name="Versão atual"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Versão",
                "verbose_name_plural": "Versões",
                "ordering": ["-inicio"],
            },
        ),
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_completo",
                    models.CharField(
                        max_length=300, unique=True, verbose_name="Nome completo"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=300)),
                (
                    "rotulo",
                    models.CharField(blank=True, max_length=200, verbose_name="Rótulo"),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turmas",
                        to="horarios.curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Turma",
                "verbose_name_plural": "Turmas",
                "ordering": ["curso__posicao", "nome_completo"],
            },
        ),
        migrations.CreateModel(
            name="Aula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "atividade_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Activity Id"
                    ),
                ),
                (
                    "disciplina",
                    models.CharField(max_length=200, verbose_name="Disciplina"),
                ),
                (
                    "dia_semana",
                    models.CharField(max_length=30, verbose_name="Dia da semana"),
                ),
                (
                    "hora_inicio",
                    models.CharField(max_length=5, verbose_name="Hora início"),
                ),
                ("hora_fim", models.CharField(max_length=5, verbose_name="Hora fim")),
                (
                    "tag",
                    models.CharField(blank=True, max_length=30, verbose_name="Tag"),
                ),
                (
                    "professores",
                    models.ManyToManyField(
                        blank=True, related_name="aulas", to="horarios.professor"
                    ),
                ),
                (
                    "sala",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aulas",
                        to="horarios.sala",
                    ),
                ),
                (
                    "turmas",
                    models.ManyToManyField(
                        blank=True, related_name="aulas", to="horarios.turma"
                    ),
                ),
                (
                    "versao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aulas",
                        to="horarios.versao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aula",
                "verbose_name_plural": "Aulas",
                "ordering": ["dia_semana", "hora_inicio"],
            },
        ),
    ]
